### POST request to create a patient Entity
POST http://127.0.0.1:4000/patients
Content-Type: application/json

{
  "name": "Aditya_billing_service",
  "email": "adi_billing_service@gmail.com",
  "address": "aa",
  "dateOfBirth": "2002-01-02",
  "registeredDate": "2002-01-02"
}
###